import { Footer, Header } from './index';
import '../sass/globals.sass';

import { Roboto } from 'next/font/google';

export const metadata = {
  title: 'Future Store',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['100', '300', '500', '700'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
